# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515ad5d7ebdc486fc18d8bfd79ea40090cc6f6afbdbcedf339fdb9e4b466a74d0faffefe29aaacef419f87a517e103917e8651777431b3c922b8f316e2377f45

test:
  secret_key_base: 334b3d7eb2dc172ad3f2b45a8fc94be2f849a0355cb5fbe128dc0f83249d2eaafbf076b5d975105f1514739ff40211872845114491e87674886463acbbc4a34a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
